package com.chequeprint.service;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import okhttp3.MediaType;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;

import java.io.IOException;
import java.util.Collections;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Logger;

/**
 * Service for interacting with the Google Gemini API using OkHttp.
 */
public class AIService {

    private static final Logger LOGGER = Logger.getLogger(AIService.class.getName());
    
    // Using a modern model for fast text generation
    private static final String MODEL = "gemini-1.5-flash"; 
    private static final String BASE_URL = "https://generativelanguage.googleapis.com/v1beta/models/" + MODEL + ":generateContent";

    private final OkHttpClient client;
    private final ObjectMapper objectMapper;

    public AIService() {
        this.client = new OkHttpClient();
        this.objectMapper = new ObjectMapper();
    }

    /**
     * Safely retrieves the API key from environment variables.
     * NEVER hardcode your API keys directly into source code!
     */
    private String getApiKey() {
        return System.getenv("GEMINI_API_KEY");
    }

    /**
     * Sends a prompt to the Gemini AI and retrieves the text response.
     * 
     * @param prompt The message to send to the AI
     * @return The AI's response text, or an error message if the call fails
     */
    public String askAI(String prompt) {
        String apiKey = getApiKey();
        
        // Safety check: Don't attempt API call if key is missing
        if (apiKey == null || apiKey.trim().isEmpty()) {
            return "Error: Gemini API key is not configured. Please set the GEMINI_API_KEY environment variable.";
        }

        try {
            String url = BASE_URL + "?key=" + apiKey;
            String jsonBody = buildJsonPayload(prompt);
            
            RequestBody body = RequestBody.create(jsonBody, MediaType.get("application/json; charset=utf-8"));

            Request request = new Request.Builder()
                    .url(url)
                    .post(body)
                    .header("Content-Type", "application/json")
                    .build();

            // Execute the OkHttp request synchronously
            try (Response response = client.newCall(request).execute()) {
                if (!response.isSuccessful()) {
                    String errorBody = response.body() != null ? response.body().string() : "No body";
                    LOGGER.severe("API Error: HTTP " + response.code() + " - " + errorBody);
                    return "Error: The AI API returned a " + response.code() + " error.";
                }

                if (response.body() == null) {
                    return "Error: Received empty response from AI API.";
                }

                // Parse the response successfully
                return extractTextResponse(response.body().string());
            }

        } catch (IOException e) {
            LOGGER.severe("Network Error: " + e.getMessage());
            return "Error: Unable to connect to the AI API. Check your internet connection.";
        } catch (Exception e) {
            LOGGER.severe("Processing Error: " + e.getMessage());
            return "Error: An unexpected error occurred while parsing the AI response.";
        }
    }

    /**
     * Formats the prompt into the specific JSON structure required by Gemini.
     */
    private String buildJsonPayload(String prompt) throws Exception {
        Map<String, Object> textPart = new HashMap<>();
        textPart.put("text", prompt);

        Map<String, Object> contentPart = new HashMap<>();
        contentPart.put("parts", Collections.singletonList(textPart));

        Map<String, Object> root = new HashMap<>();
        root.put("contents", Collections.singletonList(contentPart));

        return objectMapper.writeValueAsString(root);
    }

    /**
     * Traverses the response JSON tree to extract the actual text generated by Gemini.
     */
    private String extractTextResponse(String jsonResponse) throws Exception {
        JsonNode rootNode = objectMapper.readTree(jsonResponse);
        
        JsonNode candidates = rootNode.path("candidates");
        if (candidates.isArray() && !candidates.isEmpty()) {
            JsonNode content = candidates.get(0).path("content");
            JsonNode parts = content.path("parts");
            
            if (parts.isArray() && !parts.isEmpty()) {
                return parts.get(0).path("text").asText();
            }
        }
        
        throw new IllegalStateException("Failed to extract text from Gemini JSON response.");
    }

    /**
     * Extracts structured cheque data (JSON) from raw OCR text using Gemini.
     */
    public String extractChequeData(String ocrText) {
        String prompt = "Extract the cheque details from the following text. You MUST return ONLY a valid JSON object with the keys: 'payee', 'amount_number', 'amount_words', 'date'. Do not include markdown blocks, just the raw JSON string.\nText:\n" + ocrText;
        return askAI(prompt);
    }
}
