package com.chequeprint.service;

public enum Permission {
  VIEW_DASHBOARD,
  VIEW_CHEQUES,
  CREATE_CHEQUE,
  UPDATE_CHEQUE,
  DELETE_CHEQUE,
  SUBMIT_CHEQUE,
  APPROVE_CHEQUE,
  REJECT_CHEQUE,
  PRINT_CHEQUE,
  VIEW_INVOICES,
  VIEW_BANK_TEMPLATES,
  ACCESS_AI_ASSISTANT,
  VIEW_SUPPORT,
  VIEW_PROFILE,
  UPDATE_PROFILE,
  MANAGE_SETTINGS,
  MANAGE_USERS,
  VIEW_AUDIT_LOG
}
